spring:
  datasource:
    url: jdbc:h2:mem:organizadordetimes
    username: 1234
    password:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false